/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "Pio",
    "x": 6473.391565063974,
    "z": -1015.2411551897178
  },
  {
    "name": "KrzychuBlazeR",
    "x": 6698.818477358476,
    "z": -916.5956350086564
  }
]
