/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "Pio",
    "x": 6697.857822609351,
    "z": -916.0408598778617
  },
  {
    "name": "KrzychuBlazeR",
    "x": 6699.17665925497,
    "z": -916.6423914442563
  }
]
